/** @type {import('tailwindcss').Config} */
// Colors, radii, and typography scale generated directly from
// docs/DESIGN.md — do not add raw hex values or one-off font sizes
// elsewhere in the app. If a needed token doesn't exist here, that's a
// rules.md §0 situation: ask before inventing one.
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#fcfcfd',
        'surface-dim': '#dddee4',
        'surface-bright': '#fcfcfd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f7f8',
        'surface-container': '#eeeef2',
        'surface-container-high': '#e6e6eb',
        'surface-container-highest': '#dddee4',
        'on-surface': '#121317',
        'on-surface-variant': '#434656',
        'inverse-surface': '#24262e',
        'inverse-on-surface': '#f6f7f8',
        'outline': '#676c83',
        'outline-variant': '#c0c2ce',
        'surface-tint': '#29408e',
        'primary': '#1f2b67',
        'on-primary': '#ffffff',
        'primary-container': '#29408e',
        'on-primary-container': '#dae1ff',
        'inverse-primary': '#8c9ccf',
        'secondary': '#4a5578',
        'on-secondary': '#ffffff',
        'secondary-container': '#dbe1f7',
        'on-secondary-container': '#3c4665',
        'tertiary': '#0e4d4a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#146b66',
        'on-tertiary-container': '#c8ece8',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#8c9ccf',
        'primary-fixed-dim': '#4560bc',
        'on-primary-fixed': '#051944',
        'on-primary-fixed-variant': '#1f2b67',
        'secondary-fixed': '#dbe1f7',
        'secondary-fixed-dim': '#b7c1e1',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#3c4665',
        'tertiary-fixed': '#c8ece8',
        'tertiary-fixed-dim': '#8ecfc8',
        'on-tertiary-fixed': '#00201d',
        'on-tertiary-fixed-variant': '#0e4d4a',
        'background': '#fcfcfd',
        'on-background': '#121317',
        'surface-variant': '#dddee4',
        'accent': '#2563eb',
        'on-accent': '#ffffff',
        'accent-container': '#dbe9fe',
        'on-accent-container': '#0a3a8c',
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', fontWeight: '500', letterSpacing: '0.05em' }],
        'code-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
      },
      fontFamily: {
        sans: ['Hanken Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
